import './globals.css';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from '../components/providers';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider>
                    <main className="flex flex-col">
                        <header className="w-full flex justify-center bg-slate-700">
                            <Header />
                        </header>
                        <section>{children}</section>
                        <footer>
                            <Footer />
                        </footer>
                    </main>
                </NextAuthProvider>
            </body>
        </html>
    );
}
